tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'railwaycat/emacsmacport'
tap 'homebrew/cask-fonts'

brew 'aspell'
brew 'autoconf'
brew 'checkbashisms'
brew 'cmigemo'
brew 'coreutils'
brew 'cowsay'
brew 'tmux'
brew 'neovim'
brew 'emacs-mac'
brew 'docker'
brew 'doxygen'
brew 'figlet'
brew 'gawk'
brew 'gdbm'
brew 'git'
brew 'go'
brew 'ghq'
brew 'hub'
brew 'imagemagick'
brew 'mas'
brew 'mercurial'
brew 'nkf'
brew 'nmap'
brew 'openssl'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rbenv'
brew 'ruby-build'
brew 'rbenv-communal-gems'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'shellcheck'
brew 'smartmontools'
brew 'sqlite'
brew 'stress'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tig'
brew 'tree'
brew 'wget'
brew 'fish'

cask 'aquaskk'
cask 'bartender'
cask 'bettertouchtool'
cask 'blueharvest'
#cask 'calibre'
cask 'cleanmymac'
#cask 'copyclip'
#cask 'dropbox'
cask 'docker'
cask 'geekbench'
cask 'google-chrome'
cask 'istat-menus'
cask 'visual-studio-code'
cask 'iterm2'
cask 'karabiner-elements'
cask 'kindle'
cask 'logitech-options'
cask 'onyx'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlimagesize'
cask 'quicklookase'
cask 'qlvideo'
cask 'suspicious-package'
#cask 'totalfinder'
cask 'transmit'
cask 'webpquicklook'
cask 'font-hack-nerd-font'

mas 'Blackmagic Disk Speed Test', id: 425264550
mas 'Evernote', id: 406056744
mas 'Evernote Web Clipper', id: 1481669779
mas 'Keynote', id: 409183694
mas 'Twitter', id: 409789998
mas 'The Unarchiver', id:425424353
mas 'WiFi Explorer', id: 494803304
mas 'Skitch', id: 425955336
mas 'Server', id: 883878097
mas 'Apple configurator 2', id: 1037126344
mas 'Amphetamine', id: 937984704
mas 'Speedtest by Ookla', id: 1153157709
mas 'GarageBand', id: 682658836
mas 'iMovie', id: 408981434
mas 'Pages', id: 409201541
mas 'Numbers', id: 409203825
mas 'Microsoft Remote Desktop', id: 1295203466
mas 'SoraAnnai', id: 599799247
mas 'PopClip', id: 445189367
mas 'Mactracker', id: 430255202
mas 'AdBlock for Safari', id: 1402042596

# vim: ft=conf
