language: c
os:
    - linux
      #- osx

env:
  global:
    - GOPATH=~
    - DOTPATH=~/.dotfiles

install:
    - curl -L dot.b4b4r07.com | bash

before_script:
    - cd $(dotpath)

script:
    # - make --silent test
