repos = [
    "github.com/BurntSushi/toml",
    "github.com/BurntSushi/toml/cmd/tomlv",
    "github.com/b4b4r07/gch",
    "github.com/b4b4r07/go-pipe",
    "github.com/b4b4r07/xtime",
    "github.com/cheggaaa/pb",
    "github.com/codegangsta/cli",
    "github.com/daviddengcn/go-colortext",
    "github.com/jessevdk/go-flags",
    "github.com/k0kubun/pp",
    "github.com/kyokomi/emoji",
    "github.com/mattn/go-scan",
    "github.com/mattn/gom",
    "github.com/mgutz/ansi",
    "github.com/mitchellh/gox",
    "github.com/monochromegane/hoi",
    "github.com/monochromegane/the_platinum_searcher",
    "github.com/motemen/go-colorine",
    "github.com/nsf/gocode",
    "github.com/nsf/godit",
    "github.com/rbtnn/go-filewatcher/...",
    "github.com/zmb3/gogetdoc",
    "golang.org/x/tools/cmd/guru",
    "github.com/fatih/gomodifytags",
]

[emoji]

[emoji.verbose]
pass = ":ok_woman:"
fail = ":no_good:"

[emoji.download]
pass = ":arrow_right:"
fail = ":x:"
